### ISSUE TITLE
在线编辑器报以下错误

### ISSUE THREAD

**Issue by XiaoBaiClassmate** [h7ml/amis-admin-vue#10]
### 描述问题

```markdown
在线demo报错
```

### 截屏或录像

![WWEXQA8~~FD29@)~R4AQ~6J](https://user-images.githubusercontent.com/39209286/191884841-d01a5ca1-8885-4a78-814c-e301e437affe.png)

### 版本信息

- 版本：版本 105.0.5195.127（正式版本） （64 位）
- 操作系统：window
- 浏览器：谷歌浏览器

**Comment by h7ml** [comment]
用这个 https://vue-amis-sdk.vercel.app/

**Comment by XiaoBaiClassmate** [comment]
@h7ml  感谢，https://vue-amis-sdk.vercel.app/ 这个链接没有demo 吗

**Comment by h7ml** [comment]
> @h7ml 感谢，https://vue-amis-sdk.vercel.app/ 这个链接没有demo 吗

h7ml/vue-amis-sdk: 基于amis-editor封装的vue版本，支持vue2，vue3
https://github.com/h7ml/vue-amis-sdk
