### ISSUE TITLE
打包后文件引入路径有问题，打包后的项目运行失败

### ISSUE THREAD

**Issue by AinyTong0920** [h7ml/amis-admin-vue#11]
能否根据开发平台(pc/移动)做定制化打包呢？

**Comment by h7ml** [comment]
和你描述没有关系吧？

**Comment by h7ml** [comment]
q：打包后文件引入路径有问题
a：一级二级？复现案例？
q：打包后的项目运行失败
a：失败截图?

**Comment by h7ml** [comment]
> 能否根据开发平台(pc/移动)做定制化打包呢？

能

**Comment by AinyTong0920** [comment]
https://user-images.githubusercontent.com/23329429/193234809-8c3726eb-66f4-4b7f-9a3d-3ff9b4a15eed.mp4
![image](https://user-images.githubusercontent.com/23329429/193234973-d71d4215-fe51-4b21-9609-48ec73cb59bd.png)
![image](https://user-images.githubusercontent.com/23329429/193235078-b45fab56-0c02-4410-afd4-784b8461392e.png)

我是前端小趴菜，大佬不要见笑，请多指教！

**Comment by h7ml** [comment]
> https://user-images.githubusercontent.com/23329429/193234809-8c3726eb-66f4-4b7f-9a3d-3ff9b4a15eed.mp4 ![image](https://user-images.githubusercontent.com/23329429/193234973-d71d4215-fe51-4b21-9609-48ec73cb59bd.png) ![image](https://user-images.githubusercontent.com/23329429/193235078-b45fab56-0c02-4410-afd4-784b8461392e.png)
> 
> 我是前端小趴菜，大佬不要见笑，请多指教！

/amis 代理到了 https://aisuda.bce.baidu.com/amis/

- 

![Uploading Screenshot_2022-10-01-08-53-06-616_mark.via.jpg…]()
