### ISSUE TITLE
运行时提示缺少MiniDecimal.js

### ISSUE THREAD

**Issue by yu18264881581** [h7ml/amis-admin-vue#12]
![企业微信截图_16748950363341](https://user-images.githubusercontent.com/32377415/215256142-5ab1ad12-4944-4507-bd38-860c0ebc0f25.png)

是不是我得把amis更新到最新版

**Comment by ctfang** [comment]
不打算修复了吗？

**Comment by h7ml** [comment]
> ![企业微信截图_16748950363341](https://user-images.githubusercontent.com/32377415/215256142-5ab1ad12-4944-4507-bd38-860c0ebc0f25.png)
> 
> 是不是我得把amis更新到最新版

环境。node npm 版本

**Comment by yu18264881581** [comment]
> > ![企业微信截图_16748950363341](https://user-images.githubusercontent.com/32377415/215256142-5ab1ad12-4944-4507-bd38-860c0ebc0f25.png)
> > 是不是我得把amis更新到最新版
> 
> 环境。node npm 版本

我查了下npm，这个js 在 rc-input-number 7.4.0版本移除了，降级到7.3.11才有。

**Comment by RamboWan** [comment]
> ![企业微信截图_16748950363341](https://user-images.githubusercontent.com/32377415/215256142-5ab1ad12-4944-4507-bd38-860c0ebc0f25.png)
> 
> 是不是我得把amis更新到最新版

我也是这个问题 你解决了吗

**Comment by yu18264881581** [comment]
> > ![企业微信截图_16748950363341](https://user-images.githubusercontent.com/32377415/215256142-5ab1ad12-4944-4507-bd38-860c0ebc0f25.png)
> > 是不是我得把amis更新到最新版
> 
> 我也是这个问题 你解决了吗

 rc-input-number降级到7.3.11
