### ISSUE TITLE
这个具体怎么用

### ISSUE THREAD

**Issue by wanghaisheng** [h7ml/amis-admin-vue#9]
**Question （问题描述）**
How to use component `s-table` paging

**Describe the solution you'd like （你期待的是什么？）**

**Additional context（附加信息）**

假如我看到样例里某个component 想把对应json导出来  可以是界面 也可以是某个组件  没找到地方

https://user-images.githubusercontent.com/2363295/172984809-7a13ca86-95c9-4b49-a766-b722df111e69.mp4

**Comment by wanghaisheng** [comment]
比如这种demo页面/组件 https://amis-admin-vue.vercel.app/index/pages/form#/
我怎么直接复制/导出对应的json出来

**Comment by h7ml** [comment]
> 比如这种demo页面/组件 https://amis-admin-vue.vercel.app/index/pages/form#/ 我怎么直接复制/导出对应的json出来

过几天我完善下页面json导出和拷贝功能

**Comment by XiaoBaiClassmate** [comment]
@h7ml  大佬，我有个疑问，就是我想用这个编辑器，自己编辑生成页面数据，在本项目某模块（可能我自己新增）渲染出来操作，这个方案可行吗
